services:
  - type: web
    name: msme-management
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p instance
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///instance/msme.db
      - key: SECRET_KEY
        sync: false  # This means you'll set it manually in Render dashboard