services:
  - type: web
    name: msme-management
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: PYTHON_VERSION
        value: 3.12.0